#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include "generator.h"

// generates an array of random numbers of a given size
void random(int count, int arr[])
{
    for(int i = 0; i<count; i++)
        arr[i]=rand();
}

int* gen(int count)
{
    int *array;
    char type[7];

    // printf("How long is your list of integers:\n");
    // scanf("%d", &count);

    printf("Array Type\n");
    scanf("%s", &type);

    // dynamically allocates memory for the array.
    array = (int*)malloc(count * sizeof(int));

    // srand() function sets the starting point for a series of random integers. If not called the rand() will generate the same array everytime.
    srand(time(0));

    random(count, array);

    do {
        if (strcmp(type, "random") != 0)
        {
            if (strcmp(type, "sorted") == 0)
            {
                sort(count, array);
            }
            else if (strcmp(type, "reverse") == 0)
            {
                sort(count, array);
                reverese(array, 0, count-1);
            }
            else
            {
                partial(count, array);
            }
        }
        else
        {
            break;
        }
    } while(0);

    // printf("Generated Array:\n");
    // // print elements of array
    // for(int j=0; j<count; j++)
    //     printf("%d ", array[j]);

    return array;

}

// sorts the array generated by random()
void sort(int count, int arr[])
{
    qsort(arr, count, sizeof(int), compare_ints);
}

// uses the sorted array from sort() and reverses it
void reverese(int arr[], int start, int end)
{
    int temp;
    while (start < end)
    {
        temp = arr[start];   
        arr[start] = arr[end];
        arr[end] = temp;
        start++;
        end--;
    }   
}

// sorts half of the array made by random() i.e. partially sorts the random array.
void partial(int count, int arr[])
{
    int p;
    p = count / 2;
    qsort(arr, p, sizeof(int), compare_ints);
}

// integer compare function used by the qsort() function in sort()
int compare_ints (const void *a, const void *b)
{
    const int *da = (const int *) a;
    const int *db = (const int *) b;

    return (*da > *db) - (*da < *db);
}
