#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "allSorts.h"

void random(int count, int arr[]);
int cmpfunc (const void * a, const void * b);
void sort(int count, int arr[]);
void reverese(int arr[], int start, int end);
void partial(int count, int arr[]);

int main()
{
    int count, type, *array;
    int t = clock();

    printf("How long is your list of integers:\n");
    scanf("%d", &count);

    // dynamically allocates memory for the array.
    array = (int*)malloc(count * sizeof(int));

    // srand() function sets the starting point for a series of random integers. If not called the rand() will generate the same array everytime.
    srand(time(0));

    random(count, array);
    sort(count, array);
    reverese(array, 0, count-1);
    partial(count, array);

    // print elements of array
    // for(int j=0; j<count; j++)
    //     printf("%d ", array[j]);

    t = clock() - t;
    // prints the time the program takes
    printf("\nElapsed time: %f seconds\n", ((double)t) / CLOCKS_PER_SEC);
    
    return 0;
}

// generates an array of random numbers of a given size
void random(int count, int arr[])
{
    for(int i = 0; i<count; i++)
        arr[i]=rand();
}

// sorts the array generated by random()
void sort(int count, int arr[])
{
    qsort(arr, count, sizeof(int), cmpfunc);
}

// uses the sorted array from sort() and reverses it
void reverese(int arr[], int start, int end)
{
    int temp;
    while (start < end)
    {
        temp = arr[start];   
        arr[start] = arr[end];
        arr[end] = temp;
        start++;
        end--;
    }   
}

// sorts half of the array made by random() i.e. partially sorts the random array.
void partial(int count, int arr[])
{
    int p;
    p = count / 2;
    qsort(arr, p, sizeof(int), cmpfunc);
}

// integer compare function used by the qsort() function in sort()
int cmpfunc (const void * a, const void * b)
{
   return ( *(int*)a - *(int*)b );
}